version: '2'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: bryviercraft
    ports:
      - '25565:25565'
    volumes:
      - '/data/bryviercraft/:/data'
    environment:
      - VERSION=LATEST
      - EULA=TRUE
      - MAX_PLAYERS=4
      - ENABLE_COMMAND_BLOCK=true
      - LEVEL=boobs
      - SEED=-2089467411
    tty: true
    stdin_open: true
    restart: always
